---
title: "Untitled Draft"
author: "Sayani Gupta"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
#source("../_drake.R")
```
```{r}
library(drake)
library(distributional)
library(tidyverse)
library(ggplot2)
loadd()
```


```{r}
# norm_data_n_nlev =  create_sim_nlev(nlevel = 2:30, nsim = 500, nperm = 2000)
norm_data_n_nlev
```
- Normalisation doesn't work with (max - mean(max))/sd(max) where mean and sd are computed by sampling with replacement many times.

```{r}
# plot_norm_n_nlev = plot_sim_nlev(norm_data_n_nlev, nlev = 2:20)
plot_norm_n_nlev
```

- Try with normalisation you had before but compute the mean and sd using bootstrap/permutation

```{r}
# (3,3)
```

```{r}
# (3,7)
```


```{r}
# (7,3)
```

```{r}
# distribution of last three cases simulated 500 times plotted
```





## Reproducibility

<details><summary>Reproducibility receipt</summary>

```{r}
## datetime
Sys.time()

## repository
if(requireNamespace('git2r', quietly = TRUE)) {
  git2r::repository()
} else {
  c(
    system2("git", args = c("log", "--name-status", "-1"), stdout = TRUE),
    system2("git", args = c("remote", "-v"), stdout = TRUE)
  )
}

## session info
sessionInfo()
```

</details>
